web:
  build: .
  command: bundle exec rackup -o 0.0.0.0 -p 9292
  ports:
    - '9292:9292'
  links:
    - redis
  environment:
    RACK_ENV: 'production'
  restart: always
  container_name: url_shortener_web

redis:
  image: redis:3.0.7
  volumes:
    - /data/redis
  ports:
    - '6379'
  restart: always
  container_name: url_shortener_redis
