app:
  build: .
  command: bundle exec unicorn -c config/unicorn.rb
  ports:
    - '8080:8080'
  volumes:
    - .:/app
  links:
    - redis
  container_name: url_shortener_app
  stdin_open: true
  tty: true

redis:
  image: redis:3.0.7
  ports:
    - '6379:6379'
  container_name: url_shortener_redis
