nginx:
  build: ./nginx
  links:
    - app
  ports:
    - '80:80'
  container_name: url_shortener_nginx

app:
  build: .
  command: bundle exec unicorn -c config/unicorn.production.rb
  links:
    - redis
  ports:
    - '8080'
  environment:
    RACK_ENV: 'production'
  container_name: url_shortener_app

redis:
  image: redis:3.0.7
  volumes:
    - /data/redis
  ports:
    - '6379'
  restart: always
  container_name: url_shortener_redis
